# Intelligent Systems 3: Probabilistic and Deep Learning

### Question 1: Regression and classification (42 marks)
1. Train and evaluate a least squares linear regression model predicting the value of
variable D from variables A, B and C.

In [21]:
import numpy as np
from sklearn.linear_model import LogisticRegression

TRAIN_SIZE = 60

# Loads the dataset (skipping the headers) and separates D as the class
data = np.genfromtxt('data.csv', delimiter=',', skip_header=1, dtype=float)
X = data[:,:-1]
y = data[:,-1]

[[1.2000e-02 1.0073e+01 6.4000e-02 5.3600e-01]
 [2.7900e-01 1.0496e+01 3.6700e-01 6.9600e-01]
 [1.0100e-01 1.0214e+01 1.6500e-01 7.4400e-01]
 [5.4600e-01 1.0919e+01 6.7000e-01 8.5700e-01]
 [4.5700e-01 1.0778e+01 5.6900e-01 8.7600e-01]
 [1.9000e-01 1.0355e+01 2.6600e-01 1.0080e+00]
 [6.3500e-01 1.1060e+01 7.7100e-01 1.0600e+00]
 [1.0800e+00 1.1765e+01 1.2760e+00 1.7930e+00]
 [1.2580e+00 1.2047e+01 1.4780e+00 1.7980e+00]
 [3.2160e+00 1.5149e+01 3.7000e+00 1.9580e+00]
 [2.7710e+00 1.4444e+01 3.1950e+00 2.1810e+00]
 [1.5250e+00 1.2470e+01 1.7810e+00 2.2210e+00]
 [1.1690e+00 1.1906e+01 1.3770e+00 2.2530e+00]
 [1.4360e+00 1.2329e+01 1.6800e+00 2.3680e+00]
 [2.0590e+00 1.3316e+01 2.3870e+00 2.4360e+00]
 [1.7920e+00 1.2893e+01 2.0840e+00 2.5000e+00]
 [2.2370e+00 1.3598e+01 2.5890e+00 2.5650e+00]
 [2.9490e+00 1.4726e+01 3.3970e+00 2.6930e+00]
 [3.0380e+00 1.4867e+01 3.4980e+00 2.7690e+00]
 [1.7030e+00 1.2752e+01 1.9830e+00 2.7990e+00]
 [2.3260e+00 1.3739e+01 2.6900e+00 2.8720e+00]
 [1.9700e+00 

In [16]:
# Split the data into training/testing sets
X_train = X[:-TRAIN_SIZE]
np.append(X_train, 0.15)
X_test = X[-TRAIN_SIZE:]

# Split the targets into training/testing sets
y_train = y[:-TRAIN_SIZE]
np.append(y, 2000)

print(y_train)
y_test = y[-TRAIN_SIZE:]

[  nan 0.536 0.696 0.744 0.857 0.876 1.008 1.06  1.793 1.798 1.958 2.181
 2.221 2.253 2.368 2.436 2.5   2.565 2.693 2.769 2.799 2.872 2.942 2.954
 3.148 3.152 3.185 3.288 3.313 3.486 3.546 3.552 3.652 3.699 3.831 3.842]
